FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

SRC_URI += "file://0001-support-for-TMP1075-tempsensors.patch"
SRC_URI += "file://0002-FanMain-geared-up-for-only-HPEFan-support-for-now.patch"
SRC_URI += "file://0003-IntelCPU-now-has-a-deltaTempFilter-for-reporting-tem.patch"
SRC_URI += "file://0004-Enable-FanRedundancy-handling-for-non-aspeed-fans.patch"
SRC_URI += "file://0005-fansensor-can-now-switch-between-hpe-and-other-fans-.patch"
SRC_URI += "file://0006-FanSensor-can-now-monitor-GPIO-fail-bits.patch"
SRC_URI += "file://0007-tachless-display-fix.patch"
SRC_URI += "file://0008-support-fans-with-cooling-cooled_by-associations-and.patch"
